import "../styles/globals.css";
import type { Metadata } from "next";
import { Poppins, Caveat } from "next/font/google";
import { ArticlesProvider } from "@/context/ArticlesContext";
import { Header } from "@/components/sections/Header/Header";
import { Footer } from "@/components/sections/Footer/Footer";

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

const poppins = Poppins({
   variable: "--font-poppins",
   subsets: ["latin"],
   weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const caveat = Caveat({
   variable: "--font-caveat",
   subsets: ["latin"],
   weight: ["400", "500", "600", "700"],
});

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <ArticlesProvider>
         <html lang="pt-br">
            <body
               className={`${poppins.variable} ${caveat.variable} antialiased`}
            >
               <Header />
               {children}
               <Footer />
            </body>
         </html>
      </ArticlesProvider>
   );
}
