name: CI

on:
  push:
    branches:
      - main
      - ci-test
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: windows-latest
    env:
      NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
      SITE_URL: ${{ secrets.SITE_URL }}
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.18.0'
          cache: 'npm'

      - name: Instalar dependências
        run: npm ci

      - name: Rodar lint
        run: npm run lint

      - name: Build de produção
        run: npm run build

      - name: Executar testes
        run: npm run test:unit
